version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  api:
    image: rpgapi:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - "./node:/api"
